= Touch Portal dashboards with DCS-COINS

* DCS-COINS download: https://www.digitalcombatsimulator.com/en/files/3319022/
* Discussion: https://forum.dcs.world/topic/207264-touch-portal-app/page/2/#findComment-4769257
* My L-39 dashboard: https://www.digitalcombatsimulator.com/en/files/3336442/
* My UH-1H dashboard: https://www.digitalcombatsimulator.com/en/files/3342493/

All stuff from this repository is absolutely free to use under the public domain Unlicense.
Do whatever you want with it - pages, pictures, icons, PSD files, whatever.

== Adjustments when upgrading

* If the new DCS-COINS uses new version of DCS-BIOS, remove the existing `~/Saved Games/<dcs>/Scripts/DCS-BIOS`.
Typically, you don't have to change the `Export.lua`.
After this, start the COINS setup which will install the new/compatible DCS-BIOS.

* You can adjust the default PP files (under `Munt.G_DCS-COINS\acdb`) if you need to.
You can comment it (ignore it) with `#` around values range (see record structure lower), or change the default position.

Xoomigo about the PP record structure:
====
* Aircraft Parameter ID
* TP State ID
* TP State Description (DCS-BIOS description)
* Action Type
** 0: No action
** 1: "set_state"
** 2: "fixed_step" DEC INC by 1
** 3: "variable_step" -<num> +<num>|"suggested_step":<num>
** 4: "action": arg:"TOGGLE"
** 5: "hold"/"set_state"
** 6: "connector/slider control/variable_step" (superset of "3")
* Action Step - increment/decrement value (if applicable)
* Enumerated list of options/Range of values [Note: if `#` is used around this, the parameter is disabled]
* TP Default (Starting) value

"UpTo2" specifies range from 0 to 2. Based on the option sequence in DCS-BIOS description, it should be 0 for "TAXI", 1 for "OFF" and "2" for "LANDING" - but I have found that it's not always the case.
====
