= UH-1H training notes

Communication structure:

* Pilot: Request/intentions
* ATC: Instructions
* Pilot: Confirmation

Request structure (pilot):

* Who you are talking to ("Krymsk Tower")
* Who you are ("Virgo" or "Angel flight")
* Where you are
* What is your Request and Intention ("request startup, ...")
* With what Information (?)

Instructions (ATC):

* [Your callsign]
* [ATC callsign]
* Instructions, e.g. "taxi to 04 via alpha".

Confirmation:

* Repeat instructions, e.g. "taxiing to 04 via alpha"
* Who you are (callsign, or abbreviated callsign, e.g. type + tail number)

Word "CLEARED" is only use by the tower "for take off", "to land" or "for touch and go".

Video with ground control/tower comms examples: https://youtu.be/mcAn_elsWG0

== Aerodrome radio messages

Readback is a confirmation of a critical message, which is repeated back with my call-sign at the end.

Startup and taxi:

* Pilot: "Krymsk Tower, Virgo request startup."
* ATC: "Virgo, Krymsk Tower, startup approved." +
or "Virgo, Krymsk Tower, startup approved, expect runway [XX]."
* (N/A) "Krymsk Tower, Virgo, request ATIS information."
* (N/A) "Virgo, Krymsk Tower, ATIS information [Alpha] is current, wind [direction/speed], visibility [XX], temperature [XX], altimeter [XX.XX], runway [XX] in use."
* Pilot: "Krymsk Tower, Virgo, ready to taxi."
* ATC: "Virgo, Krymsk Tower, taxi to runway [XX] via taxiway [YY]."
* Readback: "Taxi to runway [XX] via taxiway [YY], Virgo."

Hover check:

* Pilot: "(Krymsk) Tower, Virgo, at [Location on Airfield], request hover check." +
Location can be specified in number of ways, depending on the size of the airport, specific surroundings, etc.
For example:
** "at spot 3"
** "at the departure end of runway 04",
** "near runway 27 and taxiway Bravo",
** "north of runway 09 on the grass",
** or even "near the fuel pumps".
* ATC: "[Callsign], hover check approved, maintain position."

Takeoff solo:

* Pilot: "Krymsk Tower, Virgo holding short of runway [XX], ready for takeoff."
* "Virgo, Krymsk Tower, line up and wait, runway [XX]." +
or "Virgo, Krymsk Tower, cleared for takeoff runway [XX], wind [XX]."
* Readback: "Line up and wait, runway [XX], Virgo." +
or "Cleared for takeoff, runway [XX], Virgo."

Takeoff formation:

* "Krymsk Tower, Virgo holding short of runway [XX], request line-up and wait for formation."
* "Virgo, Krymsk Tower, line-up and wait runway [XX]." +
or "Krymsk Tower, Virgo formation ready for takeoff."
* "Krymsk Tower, Virgo flight of [number of helicopters], ready for takeoff, runway [XX]."
* "Virgo flight, Krymsk Tower, cleared for takeoff, runway [XX], wind [wind information]."

Rolling start:

* "Virgo flight, run 'em up." (Increase power.)
* Acknowledged by wingmen: "Two." "Three." Etc.
* "Virgo flight, rolling."

Departure:

* Leader: "Krymsk Departure, Virgo flight, airborne, passing [altitude], climbing to [altitude]."
* ATC: "Virgo flight, Krymsk Departure, radar contact, climb to [altitude], proceed on course."
* Leader: "Climb to [altitude], proceeding on course, Virgo flight."

Pattern:

Landing:

== Standard turn

* 360° turn in 2 minutes.
* With 80kt keep 12.5° bank.